apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  containers:
    - name: mynginx
      image: mynginx
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent