apiVersion: v1
kind: Pod
metadata:
  name: k8s-hello-world
  labels:
    app: k8s-hello-world
spec:
  containers:
    - name: k8s-hello-world
      image: muellermich/nodejs-hello
      ports:
        - containerPort: 8080
