version: '2'
services:
  postgres:
    container_name: clair_postgres
    networks:
      - clairnet
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    networks:
      - clairnet
    image: amouat/clair-with-wait
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    entrypoint: /wait-for-it.sh postgres:5432 -- clair
    command: [-config, /config/config.yaml]

networks:
  clairnet:
    driver: bridge